### PR TITLE
support fluentd versions 0.12.0 and later

### PR DESCRIPTION
**Pull request by richm**
Not sure how this works with fluentd 0.12 and later currently

### CODE REVIEW

**Comment by richm** [comment]
@t0ffel ptal

**Comment by t0ffel** [comment]
does it need change in `.gemspec` file?
specifically this https://github.com/ViaQ/fluent-plugin-collectd-nest/blob/master/fluent-plugin-collectd-nest.gemspec#L20

**Comment by richm** [comment]
> does it need change in .gemspec file?

Yes.  My patch changes it in the .gemspec file.

**Comment by t0ffel** [comment]
glitching..

**Pull request merged**
